//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.MDMServiceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerEntity", Namespace="lbj")]
    [System.SerializableAttribute()]
    public partial class CustomerEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string egnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string egaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string propertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salesmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icncreditcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnbankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnaccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROCESS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KLARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYSTEM_CODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.shortnameField, value) != true)) {
                    this.shortnameField = value;
                    this.RaisePropertyChanged("shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                if ((object.ReferenceEquals(this.egnameField, value) != true)) {
                    this.egnameField = value;
                    this.RaisePropertyChanged("egname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.egaddressField, value) != true)) {
                    this.egaddressField = value;
                    this.RaisePropertyChanged("egaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                if ((object.ReferenceEquals(this.propertyField, value) != true)) {
                    this.propertyField = value;
                    this.RaisePropertyChanged("property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                if ((object.ReferenceEquals(this.salesmanField, value) != true)) {
                    this.salesmanField = value;
                    this.RaisePropertyChanged("salesman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string icnname {
            get {
                return this.icnnameField;
            }
            set {
                if ((object.ReferenceEquals(this.icnnameField, value) != true)) {
                    this.icnnameField = value;
                    this.RaisePropertyChanged("icnname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.icncreditcodeField, value) != true)) {
                    this.icncreditcodeField = value;
                    this.RaisePropertyChanged("icncreditcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.icnaddressField, value) != true)) {
                    this.icnaddressField = value;
                    this.RaisePropertyChanged("icnaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string icnphone {
            get {
                return this.icnphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.icnphoneField, value) != true)) {
                    this.icnphoneField = value;
                    this.RaisePropertyChanged("icnphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                if ((object.ReferenceEquals(this.icnbankField, value) != true)) {
                    this.icnbankField = value;
                    this.RaisePropertyChanged("icnbank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                if ((object.ReferenceEquals(this.icnaccountField, value) != true)) {
                    this.icnaccountField = value;
                    this.RaisePropertyChanged("icnaccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                if ((object.ReferenceEquals(this.flagField, value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string PROCESS_ID {
            get {
                return this.PROCESS_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.PROCESS_IDField, value) != true)) {
                    this.PROCESS_IDField = value;
                    this.RaisePropertyChanged("PROCESS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DATA_CODE {
            get {
                return this.DATA_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_CODEField, value) != true)) {
                    this.DATA_CODEField = value;
                    this.RaisePropertyChanged("DATA_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string KLART {
            get {
                return this.KLARTField;
            }
            set {
                if ((object.ReferenceEquals(this.KLARTField, value) != true)) {
                    this.KLARTField = value;
                    this.RaisePropertyChanged("KLART");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string SYSTEM_CODE {
            get {
                return this.SYSTEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSTEM_CODEField, value) != true)) {
                    this.SYSTEM_CODEField = value;
                    this.RaisePropertyChanged("SYSTEM_CODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BsupplierEntity", Namespace="lbj")]
    [System.SerializableAttribute()]
    public partial class BsupplierEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string egnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string egaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string propertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salesmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RM.MDMServiceTest.ArrayOfBsupplier_collectionEntity collectionEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROCESS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KLARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYSTEM_CODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.shortnameField, value) != true)) {
                    this.shortnameField = value;
                    this.RaisePropertyChanged("shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                if ((object.ReferenceEquals(this.egnameField, value) != true)) {
                    this.egnameField = value;
                    this.RaisePropertyChanged("egname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.egaddressField, value) != true)) {
                    this.egaddressField = value;
                    this.RaisePropertyChanged("egaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                if ((object.ReferenceEquals(this.propertyField, value) != true)) {
                    this.propertyField = value;
                    this.RaisePropertyChanged("property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                if ((object.ReferenceEquals(this.salesmanField, value) != true)) {
                    this.salesmanField = value;
                    this.RaisePropertyChanged("salesman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                if ((object.ReferenceEquals(this.flagField, value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public RM.MDMServiceTest.ArrayOfBsupplier_collectionEntity collectionEntity {
            get {
                return this.collectionEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.collectionEntityField, value) != true)) {
                    this.collectionEntityField = value;
                    this.RaisePropertyChanged("collectionEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PROCESS_ID {
            get {
                return this.PROCESS_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.PROCESS_IDField, value) != true)) {
                    this.PROCESS_IDField = value;
                    this.RaisePropertyChanged("PROCESS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DATA_CODE {
            get {
                return this.DATA_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_CODEField, value) != true)) {
                    this.DATA_CODEField = value;
                    this.RaisePropertyChanged("DATA_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string KLART {
            get {
                return this.KLARTField;
            }
            set {
                if ((object.ReferenceEquals(this.KLARTField, value) != true)) {
                    this.KLARTField = value;
                    this.RaisePropertyChanged("KLART");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SYSTEM_CODE {
            get {
                return this.SYSTEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSTEM_CODEField, value) != true)) {
                    this.SYSTEM_CODEField = value;
                    this.RaisePropertyChanged("SYSTEM_CODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBsupplier_collectionEntity", Namespace="lbj", ItemName="bsupplier_collectionEntity")]
    [System.SerializableAttribute()]
    public class ArrayOfBsupplier_collectionEntity : System.Collections.Generic.List<RM.MDMServiceTest.bsupplier_collectionEntity> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bsupplier_collectionEntity", Namespace="lbj")]
    [System.SerializableAttribute()]
    public partial class bsupplier_collectionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnbankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icncreditcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string icnaccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                if ((object.ReferenceEquals(this.icnbankField, value) != true)) {
                    this.icnbankField = value;
                    this.RaisePropertyChanged("icnbank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.icnaddressField, value) != true)) {
                    this.icnaddressField = value;
                    this.RaisePropertyChanged("icnaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.icncreditcodeField, value) != true)) {
                    this.icncreditcodeField = value;
                    this.RaisePropertyChanged("icncreditcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                if ((object.ReferenceEquals(this.icnaccountField, value) != true)) {
                    this.icnaccountField = value;
                    this.RaisePropertyChanged("icnaccount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lbj", ConfigurationName="MDMServiceTest.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 lbj 的元素名称 entity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddCustomer", ReplyAction="*")]
        RM.MDMServiceTest.AddCustomerResponse AddCustomer(RM.MDMServiceTest.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<RM.MDMServiceTest.AddCustomerResponse> AddCustomerAsync(RM.MDMServiceTest.AddCustomerRequest request);
        
        // CODEGEN: 命名空间 lbj 的元素名称 supplierEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddBsupplier", ReplyAction="*")]
        RM.MDMServiceTest.AddBsupplierResponse AddBsupplier(RM.MDMServiceTest.AddBsupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddBsupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<RM.MDMServiceTest.AddBsupplierResponse> AddBsupplierAsync(RM.MDMServiceTest.AddBsupplierRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomer", Namespace="lbj", Order=0)]
        public RM.MDMServiceTest.AddCustomerRequestBody Body;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(RM.MDMServiceTest.AddCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="lbj")]
    public partial class AddCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RM.MDMServiceTest.CustomerEntity entity;
        
        public AddCustomerRequestBody() {
        }
        
        public AddCustomerRequestBody(RM.MDMServiceTest.CustomerEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomerResponse", Namespace="lbj", Order=0)]
        public RM.MDMServiceTest.AddCustomerResponseBody Body;
        
        public AddCustomerResponse() {
        }
        
        public AddCustomerResponse(RM.MDMServiceTest.AddCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="lbj")]
    public partial class AddCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddCustomerResult;
        
        public AddCustomerResponseBody() {
        }
        
        public AddCustomerResponseBody(string AddCustomerResult) {
            this.AddCustomerResult = AddCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBsupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBsupplier", Namespace="lbj", Order=0)]
        public RM.MDMServiceTest.AddBsupplierRequestBody Body;
        
        public AddBsupplierRequest() {
        }
        
        public AddBsupplierRequest(RM.MDMServiceTest.AddBsupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="lbj")]
    public partial class AddBsupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RM.MDMServiceTest.BsupplierEntity supplierEntity;
        
        public AddBsupplierRequestBody() {
        }
        
        public AddBsupplierRequestBody(RM.MDMServiceTest.BsupplierEntity supplierEntity) {
            this.supplierEntity = supplierEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBsupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBsupplierResponse", Namespace="lbj", Order=0)]
        public RM.MDMServiceTest.AddBsupplierResponseBody Body;
        
        public AddBsupplierResponse() {
        }
        
        public AddBsupplierResponse(RM.MDMServiceTest.AddBsupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="lbj")]
    public partial class AddBsupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddBsupplierResult;
        
        public AddBsupplierResponseBody() {
        }
        
        public AddBsupplierResponseBody(string AddBsupplierResult) {
            this.AddBsupplierResult = AddBsupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : RM.MDMServiceTest.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<RM.MDMServiceTest.ServiceSoap>, RM.MDMServiceTest.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RM.MDMServiceTest.AddCustomerResponse RM.MDMServiceTest.ServiceSoap.AddCustomer(RM.MDMServiceTest.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public string AddCustomer(RM.MDMServiceTest.CustomerEntity entity) {
            RM.MDMServiceTest.AddCustomerRequest inValue = new RM.MDMServiceTest.AddCustomerRequest();
            inValue.Body = new RM.MDMServiceTest.AddCustomerRequestBody();
            inValue.Body.entity = entity;
            RM.MDMServiceTest.AddCustomerResponse retVal = ((RM.MDMServiceTest.ServiceSoap)(this)).AddCustomer(inValue);
            return retVal.Body.AddCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RM.MDMServiceTest.AddCustomerResponse> RM.MDMServiceTest.ServiceSoap.AddCustomerAsync(RM.MDMServiceTest.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<RM.MDMServiceTest.AddCustomerResponse> AddCustomerAsync(RM.MDMServiceTest.CustomerEntity entity) {
            RM.MDMServiceTest.AddCustomerRequest inValue = new RM.MDMServiceTest.AddCustomerRequest();
            inValue.Body = new RM.MDMServiceTest.AddCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((RM.MDMServiceTest.ServiceSoap)(this)).AddCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RM.MDMServiceTest.AddBsupplierResponse RM.MDMServiceTest.ServiceSoap.AddBsupplier(RM.MDMServiceTest.AddBsupplierRequest request) {
            return base.Channel.AddBsupplier(request);
        }
        
        public string AddBsupplier(RM.MDMServiceTest.BsupplierEntity supplierEntity) {
            RM.MDMServiceTest.AddBsupplierRequest inValue = new RM.MDMServiceTest.AddBsupplierRequest();
            inValue.Body = new RM.MDMServiceTest.AddBsupplierRequestBody();
            inValue.Body.supplierEntity = supplierEntity;
            RM.MDMServiceTest.AddBsupplierResponse retVal = ((RM.MDMServiceTest.ServiceSoap)(this)).AddBsupplier(inValue);
            return retVal.Body.AddBsupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RM.MDMServiceTest.AddBsupplierResponse> RM.MDMServiceTest.ServiceSoap.AddBsupplierAsync(RM.MDMServiceTest.AddBsupplierRequest request) {
            return base.Channel.AddBsupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<RM.MDMServiceTest.AddBsupplierResponse> AddBsupplierAsync(RM.MDMServiceTest.BsupplierEntity supplierEntity) {
            RM.MDMServiceTest.AddBsupplierRequest inValue = new RM.MDMServiceTest.AddBsupplierRequest();
            inValue.Body = new RM.MDMServiceTest.AddBsupplierRequestBody();
            inValue.Body.supplierEntity = supplierEntity;
            return ((RM.MDMServiceTest.ServiceSoap)(this)).AddBsupplierAsync(inValue);
        }
    }
}
