//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.localService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lbj", ConfigurationName="localService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddCustomer(RM.localService.CustomerEntity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task AddCustomerAsync(RM.localService.CustomerEntity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddBsupplier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddBsupplier(RM.localService.BsupplierEntity supplierEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="lbj/AddBsupplier", ReplyAction="*")]
        System.Threading.Tasks.Task AddBsupplierAsync(RM.localService.BsupplierEntity supplierEntity);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class CustomerEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string addressField;
        
        private string egnameField;
        
        private string egaddressField;
        
        private string currencyField;
        
        private string propertyField;
        
        private string remarkField;
        
        private string salesmanField;
        
        private string icnnameField;
        
        private string icncreditcodeField;
        
        private string icnaddressField;
        
        private string icnphoneField;
        
        private string icnbankField;
        
        private string icnaccountField;
        
        private string flagField;
        
        private string pROCESS_IDField;
        
        private string dATA_CODEField;
        
        private string kLARTField;
        
        private string sYSTEM_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                this.shortnameField = value;
                this.RaisePropertyChanged("shortname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                this.egnameField = value;
                this.RaisePropertyChanged("egname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                this.egaddressField = value;
                this.RaisePropertyChanged("egaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
                this.RaisePropertyChanged("property");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
                this.RaisePropertyChanged("salesman");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string icnname {
            get {
                return this.icnnameField;
            }
            set {
                this.icnnameField = value;
                this.RaisePropertyChanged("icnname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                this.icncreditcodeField = value;
                this.RaisePropertyChanged("icncreditcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                this.icnaddressField = value;
                this.RaisePropertyChanged("icnaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string icnphone {
            get {
                return this.icnphoneField;
            }
            set {
                this.icnphoneField = value;
                this.RaisePropertyChanged("icnphone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                this.icnbankField = value;
                this.RaisePropertyChanged("icnbank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                this.icnaccountField = value;
                this.RaisePropertyChanged("icnaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PROCESS_ID {
            get {
                return this.pROCESS_IDField;
            }
            set {
                this.pROCESS_IDField = value;
                this.RaisePropertyChanged("PROCESS_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DATA_CODE {
            get {
                return this.dATA_CODEField;
            }
            set {
                this.dATA_CODEField = value;
                this.RaisePropertyChanged("DATA_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string KLART {
            get {
                return this.kLARTField;
            }
            set {
                this.kLARTField = value;
                this.RaisePropertyChanged("KLART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class bsupplier_collectionEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string icnbankField;
        
        private string icnaddressField;
        
        private string icncreditcodeField;
        
        private string icnaccountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                this.icnbankField = value;
                this.RaisePropertyChanged("icnbank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                this.icnaddressField = value;
                this.RaisePropertyChanged("icnaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                this.icncreditcodeField = value;
                this.RaisePropertyChanged("icncreditcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                this.icnaccountField = value;
                this.RaisePropertyChanged("icnaccount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class BsupplierEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string addressField;
        
        private string egnameField;
        
        private string egaddressField;
        
        private string currencyField;
        
        private string propertyField;
        
        private string remarkField;
        
        private string salesmanField;
        
        private string flagField;
        
        private bsupplier_collectionEntity[] collectionEntityField;
        
        private string pROCESS_IDField;
        
        private string dATA_CODEField;
        
        private string kLARTField;
        
        private string sYSTEM_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                this.shortnameField = value;
                this.RaisePropertyChanged("shortname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                this.egnameField = value;
                this.RaisePropertyChanged("egname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                this.egaddressField = value;
                this.RaisePropertyChanged("egaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
                this.RaisePropertyChanged("property");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
                this.RaisePropertyChanged("salesman");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("collectionEntity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bsupplier_collectionEntity[] collectionEntity {
            get {
                return this.collectionEntityField;
            }
            set {
                this.collectionEntityField = value;
                this.RaisePropertyChanged("collectionEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PROCESS_ID {
            get {
                return this.pROCESS_IDField;
            }
            set {
                this.pROCESS_IDField = value;
                this.RaisePropertyChanged("PROCESS_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DATA_CODE {
            get {
                return this.dATA_CODEField;
            }
            set {
                this.dATA_CODEField = value;
                this.RaisePropertyChanged("DATA_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string KLART {
            get {
                return this.kLARTField;
            }
            set {
                this.kLARTField = value;
                this.RaisePropertyChanged("KLART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : RM.localService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<RM.localService.ServiceSoap>, RM.localService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCustomer(RM.localService.CustomerEntity entity) {
            base.Channel.AddCustomer(entity);
        }
        
        public System.Threading.Tasks.Task AddCustomerAsync(RM.localService.CustomerEntity entity) {
            return base.Channel.AddCustomerAsync(entity);
        }
        
        public void AddBsupplier(RM.localService.BsupplierEntity supplierEntity) {
            base.Channel.AddBsupplier(supplierEntity);
        }
        
        public System.Threading.Tasks.Task AddBsupplierAsync(RM.localService.BsupplierEntity supplierEntity) {
            return base.Channel.AddBsupplierAsync(supplierEntity);
        }
    }
}
