//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace RM.WebService.ServiceClass {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="lbj")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBsupplierOperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://localhost:44070/MDMService.asmx";
        }
        
        /// <remarks/>
        public event AddCustomerCompletedEventHandler AddCustomerCompleted;
        
        /// <remarks/>
        public event AddBsupplierCompletedEventHandler AddBsupplierCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("lbj/AddCustomer", RequestNamespace="lbj", ResponseNamespace="lbj", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddCustomer(CustomerEntity entity) {
            object[] results = this.Invoke("AddCustomer", new object[] {
                        entity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddCustomer(CustomerEntity entity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddCustomer", new object[] {
                        entity}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAddCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddCustomerAsync(CustomerEntity entity) {
            this.AddCustomerAsync(entity, null);
        }
        
        /// <remarks/>
        public void AddCustomerAsync(CustomerEntity entity, object userState) {
            if ((this.AddCustomerOperationCompleted == null)) {
                this.AddCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCustomerOperationCompleted);
            }
            this.InvokeAsync("AddCustomer", new object[] {
                        entity}, this.AddCustomerOperationCompleted, userState);
        }
        
        private void OnAddCustomerOperationCompleted(object arg) {
            if ((this.AddCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCustomerCompleted(this, new AddCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("lbj/AddBsupplier", RequestNamespace="lbj", ResponseNamespace="lbj", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddBsupplier(BsupplierEntity supplierEntity) {
            object[] results = this.Invoke("AddBsupplier", new object[] {
                        supplierEntity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddBsupplier(BsupplierEntity supplierEntity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddBsupplier", new object[] {
                        supplierEntity}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAddBsupplier(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddBsupplierAsync(BsupplierEntity supplierEntity) {
            this.AddBsupplierAsync(supplierEntity, null);
        }
        
        /// <remarks/>
        public void AddBsupplierAsync(BsupplierEntity supplierEntity, object userState) {
            if ((this.AddBsupplierOperationCompleted == null)) {
                this.AddBsupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBsupplierOperationCompleted);
            }
            this.InvokeAsync("AddBsupplier", new object[] {
                        supplierEntity}, this.AddBsupplierOperationCompleted, userState);
        }
        
        private void OnAddBsupplierOperationCompleted(object arg) {
            if ((this.AddBsupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBsupplierCompleted(this, new AddBsupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class CustomerEntity {
        
        private string codeField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string addressField;
        
        private string egnameField;
        
        private string egaddressField;
        
        private string currencyField;
        
        private string propertyField;
        
        private string remarkField;
        
        private string salesmanField;
        
        private string icnnameField;
        
        private string icncreditcodeField;
        
        private string icnaddressField;
        
        private string icnphoneField;
        
        private string icnbankField;
        
        private string icnaccountField;
        
        private string flagField;
        
        private string pROCESS_IDField;
        
        private string dATA_CODEField;
        
        private string kLARTField;
        
        private string sYSTEM_CODEField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                this.shortnameField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                this.egnameField = value;
            }
        }
        
        /// <remarks/>
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                this.egaddressField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        public string icnname {
            get {
                return this.icnnameField;
            }
            set {
                this.icnnameField = value;
            }
        }
        
        /// <remarks/>
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                this.icncreditcodeField = value;
            }
        }
        
        /// <remarks/>
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                this.icnaddressField = value;
            }
        }
        
        /// <remarks/>
        public string icnphone {
            get {
                return this.icnphoneField;
            }
            set {
                this.icnphoneField = value;
            }
        }
        
        /// <remarks/>
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                this.icnbankField = value;
            }
        }
        
        /// <remarks/>
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                this.icnaccountField = value;
            }
        }
        
        /// <remarks/>
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_ID {
            get {
                return this.pROCESS_IDField;
            }
            set {
                this.pROCESS_IDField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_CODE {
            get {
                return this.dATA_CODEField;
            }
            set {
                this.dATA_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string KLART {
            get {
                return this.kLARTField;
            }
            set {
                this.kLARTField = value;
            }
        }
        
        /// <remarks/>
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class bsupplier_collectionEntity {
        
        private string icnbankField;
        
        private string icnaddressField;
        
        private string icncreditcodeField;
        
        private string icnaccountField;
        
        /// <remarks/>
        public string icnbank {
            get {
                return this.icnbankField;
            }
            set {
                this.icnbankField = value;
            }
        }
        
        /// <remarks/>
        public string icnaddress {
            get {
                return this.icnaddressField;
            }
            set {
                this.icnaddressField = value;
            }
        }
        
        /// <remarks/>
        public string icncreditcode {
            get {
                return this.icncreditcodeField;
            }
            set {
                this.icncreditcodeField = value;
            }
        }
        
        /// <remarks/>
        public string icnaccount {
            get {
                return this.icnaccountField;
            }
            set {
                this.icnaccountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="lbj")]
    public partial class BsupplierEntity {
        
        private string codeField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string addressField;
        
        private string egnameField;
        
        private string egaddressField;
        
        private string currencyField;
        
        private string propertyField;
        
        private string remarkField;
        
        private string salesmanField;
        
        private string flagField;
        
        private bsupplier_collectionEntity[] collectionEntityField;
        
        private string pROCESS_IDField;
        
        private string dATA_CODEField;
        
        private string kLARTField;
        
        private string sYSTEM_CODEField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string shortname {
            get {
                return this.shortnameField;
            }
            set {
                this.shortnameField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string egname {
            get {
                return this.egnameField;
            }
            set {
                this.egnameField = value;
            }
        }
        
        /// <remarks/>
        public string egaddress {
            get {
                return this.egaddressField;
            }
            set {
                this.egaddressField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        public bsupplier_collectionEntity[] collectionEntity {
            get {
                return this.collectionEntityField;
            }
            set {
                this.collectionEntityField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_ID {
            get {
                return this.pROCESS_IDField;
            }
            set {
                this.pROCESS_IDField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_CODE {
            get {
                return this.dATA_CODEField;
            }
            set {
                this.dATA_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string KLART {
            get {
                return this.kLARTField;
            }
            set {
                this.kLARTField = value;
            }
        }
        
        /// <remarks/>
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void AddCustomerCompletedEventHandler(object sender, AddCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void AddBsupplierCompletedEventHandler(object sender, AddBsupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBsupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBsupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
