//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// 适配器
/// 
/// </remarks>
public class Adapter : Target
{
	public virtual object Adaptee
	{
		get;
		set;
	}

	public virtual Adaptee Adaptee
	{
		get;
		set;
	}

	public virtual void Request()
	{
		throw new System.NotImplementedException();
	}

}

