//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Barbecuer
{
	public virtual BakeMuttomOrder BakeMuttomOrder
	{
		get;
		set;
	}

	public virtual BakeChickenWingOrder BakeChickenWingOrder
	{
		get;
		set;
	}

	public virtual void BakeMutton()
	{
		throw new System.NotImplementedException();
	}

	public virtual void BakeChickenWing()
	{
		throw new System.NotImplementedException();
	}

}

