//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Waiter
{
	public virtual object IList<Command>
	{
		get;
		set;
	}

	public virtual abstract  Command abstract  Command
	{
		get;
		set;
	}

	public virtual void SetOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CancelOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Notify()
	{
		throw new System.NotImplementedException();
	}

}

